'use client';

import { useState } from 'react';
import { useAppStore } from '@/lib/store';

export default function ExportModal() {
  const { showExport, setShowExport, nodes, edges, variables, workflowName } = useAppStore();
  const [activeTab, setActiveTab] = useState<'json' | 'python' | 'png'>('json');

  if (!showExport) return null;

  const workflowJson = JSON.stringify(
    {
      name: workflowName,
      version: 1,
      exportedAt: new Date().toISOString(),
      nodes: nodes.map((n) => ({
        id: n.id,
        type: n.type,
        label: (n.data as { label: string }).label,
        position: n.position,
        config: (n.data as { config?: unknown }).config,
      })),
      edges: edges.map((e) => ({
        id: e.id,
        source: e.source,
        target: e.target,
        label: e.label,
      })),
      variables: variables,
    },
    null,
    2,
  );

  const pythonCode = `# Auto-generated by LEMON
# Workflow: ${workflowName}
# Generated: ${new Date().toISOString()}

def ${workflowName.toLowerCase().replace(/\s+/g, '_')}(${variables.filter(v => !v.isDerived).map(v => v.name + ': ' + (v.type === 'number' ? 'float' : v.type === 'boolean' ? 'bool' : 'str')).join(', ')}):
    """${workflowName} - Decision Workflow"""
    
    # Decision: Age >= 65?
    if age >= 65:
        # Calculation: Risk Score
        risk_score = age + 10
        
        # Decision: Risk Score > 75?
        if risk_score > 75:
            # Process: Cardiology Referral
            return "Immediate cardiology referral"
        else:
            return "Admit for observation"
    else:
        # Decision: Has Chest Pain?
        if has_chest_pain:
            # Process: Urgent Assessment
            return "Admit for observation"
        else:
            # Process: Standard Assessment
            return "Discharge with follow-up"


# Example usage:
if __name__ == "__main__":
    result = ${workflowName.toLowerCase().replace(/\s+/g, '_')}(
        age=72,
        has_chest_pain=True,
        blood_pressure=160,
        pain_duration=30,
        risk_category="High"
    )
    print(f"Recommendation: {result}")
`;

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownload = () => {
    if (activeTab === 'json') {
      downloadFile(workflowJson, `${workflowName.replace(/\s+/g, '_')}.json`, 'application/json');
    } else if (activeTab === 'python') {
      downloadFile(pythonCode, `${workflowName.replace(/\s+/g, '_')}.py`, 'text/x-python');
    } else {
      // PNG - use html-to-image on the React Flow viewport
      alert('PNG export would capture the React Flow canvas. In production, this uses html-to-image library.');
    }
  };

  const tabs = [
    { id: 'json' as const, label: 'JSON', icon: '{ }' },
    { id: 'python' as const, label: 'Python', icon: '🐍' },
    { id: 'png' as const, label: 'PNG', icon: '🖼' },
  ];

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50" onClick={() => setShowExport(false)}>
      <div className="bg-white rounded-xl shadow-2xl w-[700px] max-h-[80vh] flex flex-col" onClick={(e) => e.stopPropagation()}>
        <div className="p-4 border-b border-gray-200 flex items-center justify-between shrink-0">
          <h2 className="text-lg font-bold text-gray-800">Export Workflow</h2>
          <button onClick={() => setShowExport(false)} className="text-gray-400 hover:text-gray-600 text-2xl leading-none">&times;</button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-200 shrink-0">
          {tabs.map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex-1 py-3 text-sm font-medium transition-colors ${
                activeTab === tab.id
                  ? 'border-b-2 border-blue-600 text-blue-600 bg-blue-50'
                  : 'text-gray-500 hover:text-gray-700 hover:bg-gray-50'
              }`}
            >
              {tab.icon} {tab.label}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4">
          {activeTab === 'json' && (
            <pre className="bg-gray-900 text-green-400 rounded-lg p-4 text-xs font-mono overflow-x-auto max-h-[400px] overflow-y-auto">
              {workflowJson}
            </pre>
          )}
          {activeTab === 'python' && (
            <pre className="bg-gray-900 text-blue-300 rounded-lg p-4 text-xs font-mono overflow-x-auto max-h-[400px] overflow-y-auto">
              {pythonCode}
            </pre>
          )}
          {activeTab === 'png' && (
            <div className="text-center py-12">
              <div className="text-6xl mb-4">🖼</div>
              <p className="text-gray-600 text-sm">PNG export captures the workflow canvas as an image</p>
              <p className="text-gray-400 text-xs mt-2">Uses html-to-image library to render the React Flow viewport</p>
              <div className="mt-4 bg-gray-100 rounded-lg p-8 border-2 border-dashed border-gray-300">
                <p className="text-gray-400 text-sm">Canvas preview would appear here</p>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-gray-200 flex justify-end gap-2 shrink-0">
          <button onClick={() => setShowExport(false)} className="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">
            Cancel
          </button>
          <button onClick={handleDownload} className="px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium">
            ↓ Download {activeTab.toUpperCase()}
          </button>
        </div>
      </div>
    </div>
  );
}
